version: 2.1
jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            chmod +x ./gradlew
            ./gradlew test
      - store_test_results:
          path: build/reports/tests/test
      - store_artifacts:
          path: build/reports/tests/test
workflows:
  version: 2.1
  workflow:
    jobs:
    - build