version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
        name: Run tests
        command:
          ./gradlew test
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
workflows:
  version: 2.1
  workflow:
    jobs:
    - build